---

- name: Install WordPress
  hosts: wordpress-server
  # user: root
  remote_user: ubuntu
  sudo: true
  become: yes
  become_method: su

  vars:
    - db_name: "{{ lookup('env','DB_NAME') }}"
    - db_user: "{{ lookup('env','DB_USER') }}"
    - db_password: "{{ lookup('env','DB_PASSWORD') }}"

  roles:
    - apt
    - lamp
    - wpress
